### ISSUE TITLE
Not retriving recent text.

### ISSUE THREAD

**Issue by ThomasWarnasch** [Dracovian/Discord-Scraper#10] opened 2019-06-22 22:44 UTC
I'm scraping a server of text and the most recent line retrieved is not up to date with the server. For me the most recent line retrieved is ~17 hours behind. Also is it possible to have the output csv in a true reverse order instead of the batches of 5?

Thank you for your time.

**Comment by Dracovian** [comment] 2019-06-23 01:39
As far as the method used to scrape contents, the script attempts to traverse from the current date (according to the system's clock) and then proceed to traverse day-by-day in reverse until it reaches the theoretical minimum of January 1, 2015 (which is a few months before Discord got released, so there's little to no chances of finding contents that far back on Discord).

The issue with that could be the method used by the script to generate the snowflake value of the minimum and maximum timestamps that the Discord client uses whenever you use search queries such as "on:".

In my testing the results of using "on:" would demand two snowflakes, one for the timestamp of the target date around 00:00:00 + the timezone offset of the nearest CDN (Content Delivery Network, which is Dallas in my case and thus UTC-6:00 or 06:00:00) without DST (Daylight Savings Time).

I'll make a couple of modifications to see if I can't determine if it's a problem with the timestamp to snowflake function or if it's a problem that can be solved by removing the timezone offset and just settling for 00:00-23:59 instead (since the Discord client was doing 06:00-23:59 in my case whenever I made any "on:" queries in the searchbar).

I'm not 100% certain about your request for a "true reverse order instead of the batches of 5" since the CSV files that are generated from DMs are built on these six columns:

channel id,
message id,
message contents,
message timestamp,
author id,
author name

And CSV files that are generated from servers are built on these seven columns:

server id,
channel id,
message id,
message contents,
message timestamp,
author id,
author name

So there's no "batches of 5" that I can see, and the CSV files should already be ordered by timestamp (from newest to oldest). The only columns that can be potentially ordered in "true reverse order" are the message contents and author name columns since those columns contain more than numerical values.

Maybe some more elaboration on that could be of help, I did try my best to prevent message formatting from messing up the CSV files but I don't feel that I have fully encompassed all possible problems that could occur when generating these CSV files.

As for the main issue of the messages being scraped not gathering the more recent texts, I do suspect the timezone offset and system clock settings could be the potential cause of the problem (as well as the script not being able to gather all of the images, videos, and files from a channel from my testing) and so I'll run some tests with and without the timezone offset to see if that fixes the problem.

**Comment by Dracovian** [comment] 2019-06-23 01:56
While looking for the potential cause of your problem I did see that I didn't put any timezone offset in the "get_day" function as I remembered doing during the development of this recent release:

![Kk9mFD4.png](https://i.imgur.com/Kk9mFD4.png)

Also I did determine what might be the cause of duplicate entries in the CSV file as this is what Discord returns when making the queries:

![Erfrz6z.png](https://i.imgur.com/Erfrz6z.png)

I did redact some information from the screenshot, but the duplicate entry issue is still there and I'll definitely have to figure out a way to prevent duplicates in the logging.

**Comment by Dracovian** [comment] 2019-06-23 02:06
The Discord API doesn't have anything in its reference pertaining to /guilds/{guild.id}/messages/search so there's no real reference point to work off of in my script aside from what I can gather from inspect element.

Whenever I do a query like "on: 2019-06-22" I end up with this as a result:
![gWvfaqu.png](https://i.imgur.com/gWvfaqu.png)

The query is filled with the following timestamps:
min_id = 2019-06-22 +05:00:00
max_id = 2019-06-23 + 05:00:00

Whenever I run the script it is attempting to send the following timestamps instead:
min_id = 2019-06-22 +00:00:00
max_id = 2019-06-23 +00:00:00

Now there's another thing in the script that may contribute to your first issue:
![dfv0cij.png](https://i.imgur.com/dfv0cij.png)

I can change this to allow for search results that may be a day ahead to account for timezone-related problems.

**Comment by ThomasWarnasch** [comment] 2019-06-23 18:20
Thanks for helping! Also the "batches of 5" I mentioned is best described if I just type up an example.

`message5
message4
message3
message2
message1
message10
message9
message8
message7
message6
message15
message14
message13
message12
message11`

It's not critical at all as I can just reorganize it afterwards with my own tool, it was just something I thought to mention while observing the other problem.

Thanks for creating such a useful tool.

**Comment by Dracovian** [comment] 2019-06-24 22:58
I believe that issue is caused by the results that Discord returns when searching for text (which may also explain the missing images and duplicate images from the earlier implementations of this script).

So far I'm thinking about having the script check the message IDs to determine if there are any duplicates since duplicate entries in the search results will still have the same message ID as one-another.

I'll update the script and run some tests before checking to see if things are working better on your end before closing this issue.

**Comment by Dracovian** [comment] 2019-11-20 13:10
I believe that I've fixed the issue with grabbing text in the experimental branch script.

```
git clone https://github.com/Dracovian/Discord-Scraper
cd Discord-Scraper
git checkout experimental
```

Make sure you back up all your scrapes beforehand since the checkout of the experimental branch will overwrite the contents of the Discord-Scraper folder to match that of the experimental branch layout.

**Closed by Dracovian** 2019-11-20 13:10 UTC
